version: '3'

services:

  web:

    image: flask_docker:latest

    deploy:
      replicas: 5

      restart_policy:
        condition: on-failure

    ports:

      - "80:80"

    environment:

      FLASK_ENV: development
